receivers:
  fluentforward:
    endpoint: 0.0.0.0:24224  # Fluentd logging receiver

  http:  # HTTP-based logging system
    endpoint: 0.0.0.0:8080

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317  # OTEL gRPC collector for traces/exceptions
      http:
        endpoint: 0.0.0.0:4318  # OTEL HTTP collector for traces/exceptions

processors:
  batch:
    send_batch_size: 10000
    timeout: 10s  # Batches telemetry data for efficient processing
  resourcedetection:
    detectors: [env, system]  # Detect resource information such as environment and system

exporters:
  clickhousetraces:
    datasource: tcp://clickhouse:9000/signoz_traces  # Export traces to Clickhouse

  clickhousemetricswrite:
    endpoint: tcp://clickhouse:9000/signoz_metrics  # Export metrics to Clickhouse
    resource_to_telemetry_conversion:
      enabled: true

  clickhouselogsexporter:
    dsn: tcp://clickhouse:9000/signoz_logs  # Export logs to Clickhouse
    timeout: 10s

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888  # For internal metrics

  extensions:
    - health_check
    - zpages
    - pprof  # These extensions allow health checks, profiling, and z-pages for debugging

  pipelines:
    traces:
      receivers: [otlp]  # Receives traces via OTEL HTTP and gRPC
      processors: [batch, resourcedetection]  # Processes trace data
      exporters: [clickhousetraces]  # Exports traces to Clickhouse

    metrics:
      receivers: [otlp]  # Receives metrics via OTEL HTTP and gRPC
      processors: [batch, resourcedetection]  # Processes metrics data
      exporters: [clickhousemetricswrite]  # Exports metrics to Clickhouse

    logs:
      receivers: [fluentforward, http]  # Receives logs from Fluentd and HTTP-based systems
      processors: [batch]  # Processes log data
      exporters: [clickhouselogsexporter]  # Exports logs to Clickhouse
